fix(#95): Added support for older and newer maven-javadoc-plugin
The path of the generated javadocs changed in 3.10.0; these changes aim to support both versions by automatically detecting the user's version

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -46,7 +46,6 @@ inputs:
   javadoc-source-folder:
     description: "Custom path for the new Javadoc"
     required: false
-    default: target/reports/apidocs
 
   # Development and testing inputs
   without-deploy: # deploy the javadoc to the GitHub Page, is used for development testing with nektos/act
@@ -90,12 +89,39 @@ runs:
     - name: Set Javadoc source folder
       id: set-javadoc-source-folder
       run: |
-        if [[ ${{ inputs.project }} == "gradle" && ${{ inputs.javadoc-source-folder }} == "target/reports/apidocs" ]]; then
-          echo "javadoc-source-folder=build/docs/javadoc" >> "$GITHUB_OUTPUT"
-        elif [ ! -d ${{ inputs.javadoc-source-folder }} ]; then
-          echo "javadoc-source-folder=target/site/apidocs" >> "$GITHUB_OUTPUT"
-        else
+        gradle_path="build/docs/javadoc"
+        maven_pre_javadoc_3_10_x="target/site/apidocs"
+        maven_post_javadoc_3_10_x="target/reports/apidocs"
+        
+        if [[ ! ${{ inputs.javadoc-source-folder }} == "" ]]; then
+          echo "::notice Using custom 'javadoc-source-folder': '${{ inputs.javadoc-source-folder }}'"
           echo "javadoc-source-folder=${{ inputs.javadoc-source-folder }}" >> "$GITHUB_OUTPUT"
+          exit 0
+        fi
+        
+        if [[ ${{ inputs.project }} == "gradle" ]]; then
+          echo "::notice No custom 'javadoc-source-folder' was provided, using default Gradle path '$gradle_path'"
+          echo "javadoc-source-folder=$gradle_path" >> "$GITHUB_OUTPUT"
+          exit 0
+        fi
+        
+        # Else assuming Maven as inputs.project for backwards compatiblity
+        subdir_prefix=""
+        if [[ ! ${{ inputs.subdirectories }} == "" ]]; then
+          subdir_prefix=$(echo $subdirectories | tr " " "\n" | head -n 1)/
+          echo "::notice Checking for maven-javadoc-plugin output in the first subdirectory '$subdir_prefix'"
+        fi
+        
+        # Checking for plugin outputs to determine maven-javadoc-plugin version
+        if [[ -d "$subdir_prefix$maven_pre_javadoc_3_10_x" ]]; then
+          echo "::notice Detected maven-javadoc-plugin output with version older than 3.10.0, using path '$maven_pre_javadoc_3_10_x'"
+          echo "javadoc-source-folder=$maven_pre_javadoc_3_10_x" >> "$GITHUB_OUTPUT"
+        elif [[ -d "$subdir_prefix$maven_post_javadoc_3_10_x" ]]; then
+          echo "::notice Detected maven-javadoc-plugin output with version newer than 3.10.0, using path '$maven_post_javadoc_3_10_x'"
+          echo "javadoc-source-folder=$maven_post_javadoc_3_10_x" >> "$GITHUB_OUTPUT"
+        else
+          echo "::error Could not find maven-javadoc-plugin output on the default path(s) ($maven_pre_javadoc_3_10_x for versions older than 3.10.0, or $maven_post_javadoc_3_10_x for 3.10.0+) and no custom value was provided for 'javadoc-source-path' input."
+          exit 1
         fi
       shell: bash
 
